/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdojo_jni_JNIArrayTest */

#ifndef _Included_com_jdojo_jni_JNIArrayTest
#define _Included_com_jdojo_jni_JNIArrayTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdojo_jni_JNIArrayTest
 * Method:    sum
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jdojo_jni_JNIArrayTest_sum
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jdojo_jni_JNIArrayTest
 * Method:    concat
 * Signature: ([Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jdojo_jni_JNIArrayTest_concat
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_jdojo_jni_JNIArrayTest
 * Method:    increment
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_jdojo_jni_JNIArrayTest_increment
  (JNIEnv *, jobject, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
