/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdojo_jni_JNIJavaObjectAccessTest */

#ifndef _Included_com_jdojo_jni_JNIJavaObjectAccessTest
#define _Included_com_jdojo_jni_JNIJavaObjectAccessTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdojo_jni_JNIJavaObjectAccessTest
 * Method:    callBack
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jdojo_jni_JNIJavaObjectAccessTest_callBack
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
