/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdojo_jni_JNIStringTest */

#ifndef _Included_com_jdojo_jni_JNIStringTest
#define _Included_com_jdojo_jni_JNIStringTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdojo_jni_JNIStringTest
 * Method:    printMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jdojo_jni_JNIStringTest_printMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jdojo_jni_JNIStringTest
 * Method:    getMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jdojo_jni_JNIStringTest_getMsg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
