/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdojo_jni_IntWrapper */

#ifndef _Included_com_jdojo_jni_IntWrapper
#define _Included_com_jdojo_jni_IntWrapper
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
